spring.application.name=demo

# SQL Configuration

spring.datasource.url=jdbc:mysql://localhost:3306/AgenciaDeViaje?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=TravelAgency
spring.datasource.password=Kamenkappa26@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Keycloak Configuration

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/TravelAgency

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/TravelAgency/protocol/openid-connect/certs

